name = "studypage"
main = "dist/server/server.js"
compatibility_date = "2026-05-31"
compatibility_flags = ["nodejs_compat_v2"]
account_id = "461422f5f136a7492f1acac1fdf69004"

workers_dev = true
preview_urls = true

assets = { directory = "dist/client", binding = "ASSETS" }

routes = [
  { pattern = "100mini.com", custom_domain = true },
  { pattern = "www.100mini.com", custom_domain = true },
]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "studypage"

[[d1_databases]]
binding = "D1"
database_name = "studypage"
database_id = "d9cb55d2-039e-4235-91a9-f7be9f92b469"

[vars]
R2_ACCOUNT_ID = "461422f5f136a7492f1acac1fdf69004"
R2_BUCKET_NAME = "studypage"
BETTER_AUTH_URL = "https://www.100mini.com"